# Generated by Django 4.1.2 on 2022-11-08 06:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='ingredient_group',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='recipe.ingredientgroup'),
        ),
    ]
