# Generated by Django 4.1.2 on 2022-11-01 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0002_rename_recipeinstruction_instruction_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
